"""Generator for AI Context documents."""

from typing import Dict, Any, Optional, Tuple

DEFAULT_SECTIONS: Tuple[str, ...] = (
    "structure",
    "metrics",
    "patterns",
    "dependencies",
    "git",
    "qgis",
)


class AIContextGenerator:
    """Generator for AI Context documents.

    Formats project analysis data into a structured Markdown file optimized
    for LLM consumption. Uses specialized builders for different sections;
    sections can be toggled via the ``context.sections`` config key.
    """

    def __init__(self, analyses: Dict[str, Any], project_name: str, config: Optional[Dict] = None):
        """Initialize the generator.

        Args:
            analyses: Dictionary containing all analysis results.
            project_name: Name of the project.
            config: Optional configuration dictionary (``context.sections``).
        """
        self.analyses = analyses
        self.project_name = project_name
        self.config = config or {}
        self.lines = [
            f"# AI CONTEXT - {project_name}",
            "Automatically generated by Ai-Context-Core",
            "",
        ]
        from . import (
            StructureBuilder,
            MetricsBuilder,
            PatternsBuilder,
            DependencyBuilder,
            GitTechBuilder,
            QGISBuilder,
        )

        self._builder_classes = {
            "structure": StructureBuilder,
            "metrics": MetricsBuilder,
            "patterns": PatternsBuilder,
            "dependencies": DependencyBuilder,
            "git": GitTechBuilder,
            "qgis": QGISBuilder,
        }

    def _enabled_sections(self) -> set:
        """Return the set of section names to render."""
        context_cfg = self.config.get("context") or {}
        return set(context_cfg.get("sections") or DEFAULT_SECTIONS)

    def build(self) -> str:
        """Constructs the full AI Context document.

        Returns:
            The complete Markdown content as a string.
        """
        enabled = self._enabled_sections()
        for name in DEFAULT_SECTIONS:
            if name not in enabled:
                continue
            self._builder_classes[name](self.analyses).build(self.lines)

        return "\n".join(self.lines)
