"""Generator for AI Context documents."""

from typing import Dict, Any


class AIContextGenerator:
    """Generator for AI Context documents.

    Formats project analysis data into a structured Markdown file optimized
    for LLM consumption. Uses specialized builders for different sections.
    """

    def __init__(self, analyses: Dict[str, Any], project_name: str):
        """Initialize the generator.

        Args:
            analyses: Dictionary containing all analysis results.
            project_name: Name of the project.
        """
        self.analyses = analyses
        self.project_name = project_name
        self.lines = [
            f"# AI CONTEXT - {project_name}",
            "Automatically generated by Ai-Context-Core",
            "",
        ]
        from . import (
            StructureBuilder,
            MetricsBuilder,
            PatternsBuilder,
            DependencyBuilder,
            GitTechBuilder,
        )

        self.builders = [
            StructureBuilder(analyses),
            MetricsBuilder(analyses),
            PatternsBuilder(analyses),
            DependencyBuilder(analyses),
            GitTechBuilder(analyses),
        ]

    def build(self) -> str:
        """Constructs the full AI Context document.

        Returns:
            The complete Markdown content as a string.
        """
        for builder in self.builders:
            builder.build(self.lines)

        return "\n".join(self.lines)
