"""Generator for AI Context documents."""

from typing import Any, Dict, List, Optional, Tuple

DEFAULT_SECTIONS: Tuple[str, ...] = (
    "structure",
    "metrics",
    "dependencies",
    "git",
)


class AIContextGenerator:
    """Generator for AI Context documents.

    Formats project analysis data into a structured Markdown file optimized
    for LLM consumption. Uses specialized builders for different sections;
    sections can be toggled via the ``context.sections`` config key. Sections
    are exposed individually (``build_sections``) so a token budget can be
    applied before rendering.
    """

    def __init__(self, analyses: Dict[str, Any], project_name: str, config: Optional[Dict] = None):
        """Initialize the generator.

        Args:
            analyses: Dictionary containing all analysis results.
            project_name: Name of the project.
            config: Optional configuration dictionary (``context.sections``).
        """
        self.analyses = analyses
        self.project_name = project_name
        self.config = config or {}
        self.header: List[str] = [
            f"# AI CONTEXT - {project_name}",
            "Automatically generated by Ai-Context-Core",
            "",
        ]
        from . import (
            DependencyBuilder,
            GitTechBuilder,
            MetricsBuilder,
            StructureBuilder,
        )

        self._builder_classes = {
            "structure": StructureBuilder,
            "metrics": MetricsBuilder,
            "dependencies": DependencyBuilder,
            "git": GitTechBuilder,
        }

    def _enabled_sections(self) -> set:
        """Return the set of section names to render."""
        context_cfg = self.config.get("context") or {}
        return set(context_cfg.get("sections") or DEFAULT_SECTIONS)

    def build_sections(self) -> List[Tuple[str, List[str]]]:
        """Build the enabled sections as ordered ``(name, lines)`` pairs."""
        enabled = self._enabled_sections()
        sections: List[Tuple[str, List[str]]] = []
        for name in DEFAULT_SECTIONS:
            if name not in enabled:
                continue
            lines: List[str] = []
            self._builder_classes[name](self.analyses).build(lines)
            sections.append((name, lines))
        return sections

    def build(self) -> str:
        """Construct the full AI Context document.

        Returns:
            The complete Markdown content as a string.
        """
        lines = list(self.header)
        for _name, section_lines in self.build_sections():
            lines.extend(section_lines)
        return "\n".join(lines)
